### ISSUE TITLE
Unable to view comments 

### ISSUE THREAD

**Issue by annaleaser** [ubuntu-on-reddit/redditstyle#8]
So this happens on /r/ubuntu & /r/UbuntuPodcast

basically I **cannot view any of anyone elses' comments**.

![ubuntu podcast subreddit 20jun2017](https://user-images.githubusercontent.com/25592764/27332355-6dc636de-55b9-11e7-8978-c60ac8566503.png)

I use RES, but I fail at that aswell, everytime it updates (loose all shortcuts).

Trying to reply to a comment is very difficult, if not impossible.
And please don't knock my chrome browser setup, I only use @[ecosia](https://twitter.com/Ecosia/with_replies) & ad-blockers.

Last time I came here I was happy to share, but with this flub-up; it's not cherry pie.

**Comment by Daniel-McGuire** [comment]
The subreddit in the image is not /r/Ubuntu, it's /r/UbuntuPodcast and they do not have the latest CSS... It's extremely odd. The fix is to update to the latest CSS.
